name: foodie-master

services:
  ui:
    container_name: foodie-master-ui
    image: foodie-master:ui
    build: .
    env_file: .env
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./src
          action: sync
          target: /foodie-master/src
        - path: package.json
          action: rebuild
  db:
    container_name: foodie-master-db
    image: mysql:8.4.4-oraclelinux9
    env_file: .env
    ports:
      - 3306:3306
