name: foodie-master
services:
  ui:
    container_name: foodie-master-ui
    image: foodie-master-ui
    build: .
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./src
          target: /foodie-master-ui/src
        - action: rebuild
          path: package.json
